apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: garden
  name: garden
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: garden
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: garden
    spec:
      containers:
        - image: garden
          name: garden
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
