apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: pool
  name: pool
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pool
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: pool
    spec:
      containers:
        - image: pool
          name: pool
          ports:
            - containerPort: 9090
          resources: {}
      restartPolicy: Always
status: {}
